apiVersion: v1
kind: ServiceAccount
metadata:
  name: hercules-shopify-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hercules-shopify-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hercules-shopify-reconciler
automountServiceAccountToken: false
