apiVersion: v1
kind: ServiceAccount
metadata:
  name: hercules-shopify-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hercules-shopify-worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hercules-shopify-reconciler
