import { analyzeDomainLaunch, SAUCEAPPROVED_DOMAIN } from './domain-launch.mjs';
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';
const U=Deno.env.get('SUPABASE_URL')!;const A=Deno.env.get('SUPABASE_ANON_KEY')||'';const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';const admin=createClient(U,S,{auth:{persistSession:false}});
const h={'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};const j=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:h});
function normDomain(v:string){return v.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0].replace(/\.$/,'').replace(/^www\./,'')}
async function sha(s:string){const dig=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(dig)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function ident(req:Request){const a=req.headers.get('authorization')||'';const db=createClient(U,A,{auth:{persistSession:false},global:{headers:{Authorization:a}}});const {data,error}=await db.auth.getUser();if(error||!data.user)return null;return {db,user:data.user}}
async function role(db:any,org:string,user:string){const {data}=await db.from('hercules_memberships').select('role,status').eq('organization_id',org).eq('user_id',user).eq('status','active').maybeSingle();return data?.role||null}
async function audit(org:string,user:string,action:string,type:string,id:string|null,meta:any={}){await admin.from('hercules_audit_log').insert({organization_id:org,actor_user_id:user,action,resource_type:type,resource_id:id,metadata:meta})}
async function domainAllowance(org:string){const {data:ent}=await admin.from('hercules_entitlements').select('enabled,limit_value').eq('organization_id',org).eq('feature_key','domains').maybeSingle();if(ent&&ent.enabled===false)return {ok:false,error:'domain_management_disabled',limit:0,count:0};const {count}=await admin.from('hercules_domains').select('*',{count:'exact',head:true}).eq('organization_id',org).neq('status','removed');const limit=ent?.limit_value==null?null:Number(ent.limit_value);if(limit!==null&&(count||0)>=limit)return {ok:false,error:'domain_limit_reached',limit,count:count||0};return {ok:true,limit,count:count||0}}
async function resolveDnsSafe(name:string,type:'A'|'AAAA'|'CNAME'|'NS'){try{return (await Deno.resolveDns(name,type) as any[]).map(x=>String(x||''))}catch{return []}}
async function productionStatus(db:any,org:string){const {data:d,error}=await db.from('hercules_domains').select('id,domain_name,registrar,dns_provider,status,verified_at,ssl_status,primary_target_type,primary_target_id,metadata,updated_at').eq('organization_id',org).eq('domain_name',SAUCEAPPROVED_DOMAIN).neq('status','removed').maybeSingle();if(error)throw error;if(!d)return {error:'production_domain_not_registered'};const [{data:c},a,aaaa,cname,ns]=await Promise.all([admin.from('hercules_spaceship_dns_credentials').select('status,configured_at,updated_at').eq('singleton',true).maybeSingle(),resolveDnsSafe(d.domain_name,'A'),resolveDnsSafe(d.domain_name,'AAAA'),resolveDnsSafe('www.'+d.domain_name,'CNAME'),resolveDnsSafe(d.domain_name,'NS')]);let https:any={reachable:false,status:null,location:null};try{const r=await fetch('https://'+d.domain_name,{method:'HEAD',redirect:'manual',signal:AbortSignal.timeout(7000)});https={reachable:true,status:r.status,location:r.headers.get('location')}}catch{}const launch=analyzeDomainLaunch({a,aaaa,cname,ns,credentialStatus:c?.status||'unconfigured',primaryTargetId:d.primary_target_id,sslStatus:d.ssl_status});return {domainRecord:d,credentialState:{status:c?.status||'unconfigured',configured_at:c?.configured_at||null,updated_at:c?.updated_at||null},https,launch}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:h});const id=await ident(req);if(!id)return j({error:'unauthorized'},401);const {db,user}=id;const b=req.method==='POST'?await req.json().catch(()=>({})):{};const org=String(b.organization_id||new URL(req.url).searchParams.get('organization_id')||'');if(!org)return j({error:'organization_id_required'},400);const r=await role(db,org,user.id);if(!r)return j({error:'forbidden'},403);const action=String(b.action||'list');
 if(req.method==='GET'||action==='list'){const {data,error}=await db.from('hercules_domains').select('id,domain_name,registrar,dns_provider,status,verified_at,expires_at,auto_renew,ssl_status,ssl_expires_at,primary_target_type,primary_target_id,metadata,created_at,updated_at').eq('organization_id',org).neq('status','removed').order('created_at',{ascending:false});return error?j({error:error.message},500):j({service:'Hercules Domains',version:'2.0.0',domains:data||[]});}
 if(action==='production_status'){try{return j({service:'Hercules Domains',version:'2.1.0',production:await productionStatus(db,org)})}catch(e){return j({error:e instanceof Error?e.message:'production_status_failed'},500)}}
 if(action==='production_reconcile'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);if(String(b.confirm_domain||'')!==SAUCEAPPROVED_DOMAIN)return j({error:'confirm_domain_required'},400);const state=await productionStatus(db,org);if(state?.error)return j(state,404);if(state.domainRecord?.primary_target_type!=='shopify_store')return j({error:'shopify_target_not_authorized'},409);if(state.credentialState?.status!=='configured')return j({error:'spaceship_credentials_unconfigured'},409);if(state.launch?.readiness?.dnsReady)return j({ok:true,queued:false,already_ready:true,production:state});const {data:reqId,error}=await admin.rpc('hercules_spaceship_dns_submit',{p_action:'reconcile',p_replace_custom_conflicts:true});if(error)return j({error:'spaceship_dns_submit_failed',detail:error.message},500);await audit(org,user.id,'domain.production_reconcile.queued','domain',state.domainRecord.id,{domain_name:SAUCEAPPROVED_DOMAIN,request_id:reqId,target:state.domainRecord.primary_target_id});return j({ok:true,queued:true,request_id:reqId,domain:SAUCEAPPROVED_DOMAIN,target:state.domainRecord.primary_target_id})}
 if(action==='production_reconcile_result'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);const requestId=Number(b.request_id);if(!Number.isInteger(requestId)||requestId<1)return j({error:'valid_request_id_required'},400);const {data,error}=await admin.rpc('hercules_spaceship_dns_result',{p_request_id:requestId});if(error)return j({error:'spaceship_dns_result_failed',detail:error.message},500);return j({ok:true,result:data})}
 if(action==='add'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);const allowance=await domainAllowance(org);if(!allowance.ok)return j({error:allowance.error,limit:allowance.limit,count:allowance.count},allowance.error==='domain_limit_reached'?429:403);const d=normDomain(String(b.domain_name||''));if(!d||!d.includes('.')||d.length>253)return j({error:'invalid_domain'},400);const token=crypto.randomUUID().replaceAll('-','');const hash=await sha(token);const {data,error}=await db.from('hercules_domains').insert({organization_id:org,domain_name:d,registrar:b.registrar||null,dns_provider:b.dns_provider||null,verification_method:'dns_txt',verification_token_hash:hash,metadata:{verification_record:{type:'TXT',name:`_hercules-verify.${d}`}}}).select('*').single();if(error)return j({error:error.message},400);await audit(org,user.id,'domain.created','domain',data.id,{domain_name:d});return j({domain:data,verification:{type:'TXT',name:`_hercules-verify.${d}`,value:`hercules-verification=${token}`},entitlement:{limit:allowance.limit,used_before_add:allowance.count}},201);}
 if(action==='verify'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);const did=String(b.domain_id||'');const {data:d,error}=await admin.from('hercules_domains').select('id,domain_name,status,verification_token_hash,verified_at').eq('organization_id',org).eq('id',did).maybeSingle();if(error||!d)return j({error:'domain_not_found'},404);if(d.verified_at)return j({ok:true,verified:true,domain:d.domain_name,verified_at:d.verified_at,already_verified:true});let answers:any[]=[];try{answers=await Deno.resolveDns(`_hercules-verify.${d.domain_name}`,'TXT') as any[]}catch{}const candidates:string[]=[];for(const a of answers){const s=Array.isArray(a)?a.join(''):String(a);if(s.startsWith('hercules-verification='))candidates.push(s.slice('hercules-verification='.length));}
   let matched=false;for(const c of candidates){if(await sha(c)===d.verification_token_hash){matched=true;break}}
   if(!matched){await admin.from('hercules_domain_checks').insert({domain_id:did,organization_id:org,check_type:'ownership_txt',status:'fail',details:{record:`_hercules-verify.${d.domain_name}`,answers_found:answers.length}});return j({ok:true,verified:false,domain:d.domain_name,record:`_hercules-verify.${d.domain_name}`,answers_found:answers.length});}
   const now=new Date().toISOString();const nextStatus=d.status==='active'?'active':'verified';const {data:updated,error:uerr}=await admin.from('hercules_domains').update({status:nextStatus,verified_at:now,updated_at:now}).eq('id',did).eq('organization_id',org).select('id,domain_name,status,verified_at').single();if(uerr)return j({error:uerr.message},500);await admin.from('hercules_domain_checks').insert({domain_id:did,organization_id:org,check_type:'ownership_txt',status:'pass',details:{record:`_hercules-verify.${d.domain_name}`}});await audit(org,user.id,'domain.verified','domain',did,{domain_name:d.domain_name});return j({ok:true,verified:true,domain:updated});}
 if(action==='records'){const did=String(b.domain_id||'');const {data,error}=await db.from('hercules_domain_dns_records').select('*').eq('organization_id',org).eq('domain_id',did).order('created_at');return error?j({error:error.message},500):j({records:data||[]});}
 if(action==='add_record'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);const did=String(b.domain_id||''),type=String(b.record_type||'').toUpperCase(),name=String(b.name||'').trim(),value=String(b.value||'').trim();if(!did||!['A','AAAA','CNAME','TXT','MX','NS','SRV','CAA'].includes(type)||!name||!value)return j({error:'invalid_record'},400);const {data:owned}=await db.from('hercules_domains').select('id').eq('organization_id',org).eq('id',did).neq('status','removed').maybeSingle();if(!owned)return j({error:'domain_not_found'},404);const {data,error}=await db.from('hercules_domain_dns_records').insert({domain_id:did,organization_id:org,record_type:type,name,value,ttl:b.ttl??null,priority:b.priority??null,status:'desired'}).select('*').single();if(error)return j({error:error.message},400);await audit(org,user.id,'domain.dns_record.created','dns_record',data.id,{domain_id:did,record_type:type,name});return j({record:data,execution_status:'desired_not_yet_pushed_to_provider'},201);}
 if(action==='delete_record'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);const rid=String(b.record_id||'');const {data,error}=await db.from('hercules_domain_dns_records').update({status:'deleted',updated_at:new Date().toISOString()}).eq('organization_id',org).eq('id',rid).select('id,status').single();if(error)return j({error:error.message},400);await audit(org,user.id,'domain.dns_record.deleted','dns_record',rid);return j({record:data});}
 if(action==='remove'){if(!['owner','admin'].includes(r))return j({error:'admin_required'},403);const did=String(b.domain_id||'');const now=new Date().toISOString();const {data,error}=await db.from('hercules_domains').update({status:'removed',updated_at:now}).eq('organization_id',org).eq('id',did).select('id,domain_name,status').single();if(error)return j({error:error.message},400);await audit(org,user.id,'domain.removed','domain',did,{domain_name:data.domain_name});return j({domain:data});}
 if(action==='check'){const did=String(b.domain_id||'');const {data:d}=await db.from('hercules_domains').select('id,domain_name').eq('organization_id',org).eq('id',did).neq('status','removed').maybeSingle();if(!d)return j({error:'domain_not_found'},404);const results:any[]=[];try{const dns=await Deno.resolveDns(d.domain_name,'A').catch(()=>[] as string[]);results.push({check_type:'dns_a',status:(dns as any[]).length?'pass':'fail',details:{answers:dns}})}catch{results.push({check_type:'dns_a',status:'fail',details:{}})}try{const aaaa=await Deno.resolveDns(d.domain_name,'AAAA').catch(()=>[] as string[]);results.push({check_type:'dns_aaaa',status:(aaaa as any[]).length?'pass':'warn',details:{answers:aaaa}})}catch{results.push({check_type:'dns_aaaa',status:'warn',details:{}})}try{const res=await fetch(`https://${d.domain_name}`,{method:'HEAD',redirect:'manual',signal:AbortSignal.timeout(5000)});results.push({check_type:'https',status:res.status<500?'pass':'warn',details:{status:res.status,location:res.headers.get('location')}})}catch{results.push({check_type:'https',status:'fail',details:{error:'unreachable'}})}for(const x of results)await admin.from('hercules_domain_checks').insert({domain_id:did,organization_id:org,...x});return j({domain:d.domain_name,checks:results});}
 return j({error:'unsupported_action'},400);
});