import test from "node:test";
import assert from "node:assert/strict";
import {compileForgeProject, compileFromInterpreter} from "../hercules-forge/compiler.mjs";
import {StaticForgeInterpreter} from "../hercules-forge/interpreter.mjs";
import {validateForgeSpec} from "../hercules-forge/schema.mjs";

const spec = {
  version: "0.1",
  name: "CustomerHub",
  description: "Customer workspace generated by Hercules Forge.",
  entities: [
    {
      name: "Customer",
      fields: [
        {name: "name", type: "string", required: true},
        {name: "active", type: "boolean", required: true},
      ],
    },
  ],
  pages: [
    {name: "Customers", kind: "list", entity: "Customer"},
    {name: "CustomerForm", kind: "form", entity: "Customer"},
  ],
  actions: [
    {name: "CreateCustomer", kind: "create", entity: "Customer"},
  ],
};

test("validates an owned Forge project spec", () => {
  const result = validateForgeSpec(spec);
  assert.equal(result.ok, true);
  assert.deepEqual(result.errors, []);
});

test("fails closed on invalid references", () => {
  const bad = structuredClone(spec);
  bad.pages[0].entity = "Missing";
  const result = validateForgeSpec(bad);
  assert.equal(result.ok, false);
  assert.match(result.errors.join("\n"), /unknown entity/);
});

test("compiles deterministic runnable source with loopback and request limits", () => {
  const a = compileForgeProject(spec);
  const b = compileForgeProject(spec);
  assert.equal(a.engine, "hercules-forge-owned-core");
  assert.equal(a.fingerprint, b.fingerprint);
  assert.ok(a.files["server.mjs"].includes("/health"));
  assert.ok(a.files["server.mjs"].includes('process.env.HOST ?? "127.0.0.1"'));
  assert.ok(a.files["server.mjs"].includes("MAX_BODY_BYTES"));
  assert.ok(a.files["server.mjs"].includes("FORGE_DATA_DIR"));
  assert.ok(a.files["runtime-store.mjs"].includes("atomicWrite"));
  assert.ok(a.files["runtime-store.mjs"].includes("ForgeRuntimeStore"));
  assert.match(a.files["runtime-store.mjs"], /^import .+\nimport /);
  assert.equal(a.files["runtime-store.mjs"].includes("\\nimport"), false);
  assert.ok(a.files["db/001_init.sql"].includes("Customer"));
  assert.ok(a.files["public/index.html"].includes("/app.js"));
  assert.ok(a.files["public/app.js"].includes("Customer"));
  assert.ok(a.files["public/app.css"].includes(".grid"));
});

test("escapes prompt-derived descriptions in generated HTML", () => {
  const malicious = structuredClone(spec);
  malicious.description = '<script>alert("x")</script>';
  const built = compileForgeProject(malicious);
  assert.equal(built.files["public/index.html"].includes('<script>alert("x")</script>'), false);
  assert.ok(built.files["public/index.html"].includes("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;"));
});

test("prompt interpretation is replaceable and outside the compiler", async () => {
  const result = await compileFromInterpreter(new StaticForgeInterpreter(spec), "build a customer hub");
  assert.equal(result.spec.name, "CustomerHub");
});
