import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../hercules-forge/ad-studio/index.html',import.meta.url),'utf8');
const core=html.match(/<script id="core">([\s\S]*?)<\/script>/)[1];
const S=vm.runInNewContext(core+';Studio',{URL});
const f={name:'Pilot',brand:'Hercules',product:'Pilot',audience:'Owners',problem:'Unpaid invoices',benefit:'Organized follow-up',proof:'Synthetic demo',cta:'Explore',voice:'Direct',url:''};
const sample=()=>({id:'1',form:f,ads:S.generate(f),results:[]});
test('three bounded editable messaging angles',()=>{const a=S.generate({...f,problem:'x'.repeat(1000)});assert.equal(a.length,3);assert.equal(new Set(a.map(x=>x.angle)).size,3);assert.ok(a.every(x=>x.headline.length<=120&&x.body.length<=600));});
test('metrics arithmetic and zero denominator semantics',()=>{const m=S.metrics({spend:150,impressions:10000,clicks:300,conversions:6,revenue:600});assert.equal(m.ctr,3);assert.equal(m.cpc,.5);assert.equal(m.cpa,25);assert.equal(m.roas,4);const z=S.metrics({spend:0,impressions:0,clicks:0,conversions:0,revenue:0});assert.equal(z.roas,null);assert.equal(z.cpa,null);});
test('reject negative, infinite and fractional count input',()=>{for(const value of [-1,Infinity,NaN,1.2])assert.throws(()=>S.metrics({spend:0,impressions:value,clicks:0,conversions:0,revenue:0}));});
test('budget allocation uses total envelope and validates bounds',()=>{const p=S.allocation(150,5,3);assert.equal(p.daily,30);assert.equal(p.perCreative,50);assert.equal(p.perCreativeDaily,10);for(const args of [[10,0,3],[10,2,0],[-5,2,3],[10,366,3]])assert.throws(()=>S.allocation(...args));});
test('tracking replaces UTM but preserves other query and fragment',()=>{const url=new URL(S.link('https://example.com/?ref=pilot&utm_source=old#demo',{source:'new',campaign:'hello world'}));assert.equal(url.searchParams.get('ref'),'pilot');assert.equal(url.searchParams.get('utm_source'),'new');assert.equal(url.searchParams.get('utm_campaign'),'hello world');assert.equal(url.hash,'#demo');});
test('unsafe link protocols and credentials rejected',()=>{for(const u of ['javascript:alert(1)','http://example.com','https://name:secret@example.com','bad'])assert.throws(()=>S.link(u,{}));});
test('backup round trip validates complete campaigns',()=>{const result=S.restore(JSON.parse(JSON.stringify({schema:'hercules.ad-studio.v1',campaigns:[sample()]})));assert.equal(result[0].form.brand,'Hercules');assert.equal(result[0].ads.length,3);assert.equal(result[0].plan.days,7);});
test('malformed and oversized backups rejected',()=>{for(const raw of [null,{}, {schema:'other',campaigns:[]},{schema:'hercules.ad-studio.v1',campaigns:[{}]},{schema:'hercules.ad-studio.v1',campaigns:Array(201).fill(sample())}])assert.throws(()=>S.restore(raw));});
test('restored metrics reject invalid numbers',()=>{const c=sample();c.results=[{spend:-1,impressions:0,clicks:0,conversions:0,revenue:0}];assert.throws(()=>S.restore({schema:'hercules.ad-studio.v1',campaigns:[c]}));});
test('CSV escapes quotes, commas, newline and spreadsheet formula prefixes',()=>{const out=S.csv([['=HYPERLINK("evil")','a,b','a\nb',20]]);assert.match(out,/^"'=HYPERLINK/);assert.ok(out.includes('"a,b"'));assert.ok(out.includes('"a\nb"'));});
test('runtime is standalone and uses safe DOM text rendering',()=>{assert.doesNotMatch(html,/<script[^>]+src=|fetch\(|XMLHttpRequest|innerHTML\s*=/);for(const s of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new vm.Script(s[1]));});
