import test from 'node:test';
import assert from 'node:assert/strict';
import {createStudioDirectorManifest,buildStudioProductionPlan,rehearseStudioChain,evaluateCreativeDrift,renderStudioDirector} from '../sauceapproved-studio/studio-director/core.mjs';

test('manifest defines the cross-studio control tower and remains fail-closed',()=>{const m=createStudioDirectorManifest();assert.equal(m.product,'Hercules Studio Director');assert.equal(m.executionPolicy,'route-plan-proof-handoff-fail-closed');assert.equal(m.autonomousMutation,false);assert.equal(m.autoPublish,false);assert.ok(m.differentiators.includes('Cross-Studio Project Router'));assert.ok(m.differentiators.includes('Showcase Readiness Ledger'));assert.deepEqual(m.competitionGapFeatures,['Chain-Reaction Rehearsal','Creative DNA Ledger']);});
test('campaign film routes through brand, cinema, campaign, and multichannel surfaces',()=>{const p=buildStudioProductionPlan({title:'Launch Film',goal:'cinematic launch campaign',audience:'customers',channels:['Instagram','YouTube']});assert.deepEqual(p.handoffCapsule.route,['brand-brain','movie-machine','campaign-forge','content-multiplier']);assert.equal(p.planReady,true);assert.equal(p.executionReady,false);assert.equal(p.publishReady,false);assert.ok(p.proofLedger.every(x=>x.mayExecute===false));});
test('legacy route fails closed until approved source material exists',()=>{const p=buildStudioProductionPlan({title:'Family Story',goal:'legacy documentary',audience:'family',approvedSourceCount:0});assert.equal(p.planReady,false);assert.ok(p.blockers.some(x=>x.code==='approved_source_required'));assert.ok(p.handoffCapsule.route.includes('legacy-vault'));});
test('live-stage request remains blocked pending an authorized bridge',()=>{const p=buildStudioProductionPlan({title:'Stage Spot',goal:'virtual production commercial',audience:'buyers',requiresLiveStage:true});assert.ok(p.handoffCapsule.route.includes('holostage'));assert.ok(p.blockers.some(x=>x.code==='live_stage_bridge_not_authorized'));assert.equal(p.executionReady,false);});
test('kids work always enters the dedicated safety lane',()=>{const p=buildStudioProductionPlan({title:'Kids Story',goal:'animated story',audience:'children',childMode:true});assert.ok(p.handoffCapsule.route.includes('kids'));assert.ok(p.proofLedger.some(x=>x.gate==='kids-safety-review'));});
test('incomplete briefs are rejected',()=>{assert.throws(()=>buildStudioProductionPlan({title:'Missing'}),/studio_director_brief_incomplete/);});
test('public showcase renderer exposes the control-tower contract',()=>{const html=renderStudioDirector();assert.match(html,/Hercules<br>Studio Director/);assert.match(html,/CROSS-STUDIO PROJECT ROUTER/);assert.match(html,/SHOWCASE READINESS LEDGER/);assert.match(html,/HANDOFF CAPSULE/);});
test('Chain-Reaction Rehearsal shows downstream blast radius without executing anything',()=>{const p=buildStudioProductionPlan({title:'Launch Film',goal:'cinematic launch campaign',audience:'customers',channels:['Instagram','YouTube']});const rehearsal=rehearseStudioChain(p,{failedGates:['director-proof-review']});assert.equal(rehearsal.executionAttempted,false);assert.equal(rehearsal.publishAttempted,false);const movie=rehearsal.stages.find(x=>x.surfaceId==='movie-machine');const campaign=rehearsal.stages.find(x=>x.surfaceId==='campaign-forge');const multiplier=rehearsal.stages.find(x=>x.surfaceId==='content-multiplier');assert.equal(movie.outcome,'blocked-at-gate');assert.equal(campaign.outcome,'blocked-by-upstream');assert.equal(multiplier.outcome,'blocked-by-upstream');assert.ok(rehearsal.blastRadius.includes('campaign-forge'));});
test('Creative DNA Ledger detects protected-intent drift across handoffs',()=>{const p=buildStudioProductionPlan({title:'Launch Film',goal:'cinematic launch campaign',audience:'customers',channels:['Instagram','YouTube']});assert.match(p.creativeDnaLedger.fingerprint,/^[0-9a-f]{64}$/);const same=evaluateCreativeDrift(p,{goal:'cinematic launch campaign',audience:'customers',channels:['YouTube','Instagram']});assert.equal(same.driftDetected,false);const changed=evaluateCreativeDrift(p,{goal:'cinematic launch campaign',audience:'children',channels:['Instagram','YouTube']});assert.equal(changed.driftDetected,true);assert.ok(changed.changedDimensions.includes('audience'));assert.equal(changed.requiresApproval,true);});
test('public renderer exposes both new competition-gap features',()=>{const html=renderStudioDirector();assert.match(html,/CHAIN-REACTION REHEARSAL/);assert.match(html,/CREATIVE DNA LEDGER/);});
