import {createHmac} from "node:crypto";
import {createSmokeScreenDecision,createSmokeScreenEnforcementPlan} from "./smokescreen-agent.mjs";
const ALLOWED_MODES=new Set(["OBSERVE_ONLY"]); const ALLOWED_METHODS=new Set(["GET","HEAD","POST","PUT","PATCH","DELETE","OPTIONS"]);
const ALLOWED_SIGNALS=new Set(["failedAuthAttempts","routeProbes","enumerationPattern","privilegeBoundaryProbe","honeytokenTouched","abnormalMutationBurst","impossibleWorkflowSequence"]);
function keyBytes(value){const key=Buffer.isBuffer(value)?Buffer.from(value):Buffer.from(String(value??""),"utf8");if(key.length<32)throw new Error("hmacKey must be at least 32 bytes");return key;}
function cleanMethod(value){const method=String(value??"GET").toUpperCase();return ALLOWED_METHODS.has(method)?method:"OTHER";}
function cleanRoute(value){const route=String(value??"/").split("?")[0].slice(0,256);return route.startsWith("/")?route:"/";}
function cleanSignals(value){if(!value||typeof value!=="object"||Array.isArray(value))return {};const clean={};for(const name of ALLOWED_SIGNALS)if(Object.hasOwn(value,name))clean[name]=value[name];return clean;}
function sessionRef(key,value){return "sess_"+createHmac("sha256",key).update(String(value??"anonymous")).digest("hex").slice(0,24);}
export function createSmokeScreenIngressObserver({hmacKey,mode="OBSERVE_ONLY",sink=()=>{},now=()=>Date.now()}={}){const key=keyBytes(hmacKey);if(!ALLOWED_MODES.has(mode))throw new Error("only OBSERVE_ONLY is supported by this ingress adapter");if(typeof sink!=="function")throw new Error("sink must be a function");return Object.freeze({mode,async observe(input={}){const request={sessionId:String(input.sessionId??"anonymous").slice(0,256),route:cleanRoute(input.route),method:cleanMethod(input.method),signals:cleanSignals(input.signals)};const decision=createSmokeScreenDecision(request,{hmacKey:key});const wouldEnforce=createSmokeScreenEnforcementPlan(decision);const event=Object.freeze({schema:"hercules.smokescreen.ingress-observation.v1",mode,observedAt:new Date(Number(now())).toISOString(),sessionRef:sessionRef(key,request.sessionId),method:request.method,route:request.route,decision:Object.freeze({action:decision.action,routeMode:decision.routeMode,score:decision.score,policyVersion:decision.policyVersion}),wouldEnforce:Object.freeze({mode:wouldEnforce.mode,fallback:wouldEnforce.fallback,realAssetAccess:wouldEnforce.realAssetAccess,executionAuthority:wouldEnforce.executionAuthority,outboundCounterattack:wouldEnforce.outboundCounterattack})});let telemetryRecorded=true;try{await sink(event);}catch{telemetryRecorded=false;}return Object.freeze({schema:"hercules.smokescreen.ingress-result.v1",mode,action:"PASS",routeMode:"REAL",enforced:false,realAssetAccess:true,outboundCounterattack:false,telemetryRecorded,decision,wouldEnforce});}});}

// Reconciled onto current main; observe-only boundary intentionally remains explicit.
