function clean(v){return String(v??'').trim();}
function list(v){return Array.isArray(v)?v:[];}
export function createPerformanceLabManifest(){
 return Object.freeze({schema:'sauceapproved.studio.performance-lab.manifest',version:1,product:'Hercules Performance Lab',category:'directed-digital-performance',executionPolicy:'consent-plan-proof-perform-fail-closed',autoPublish:false,autonomousMutation:false,differentiators:Object.freeze(['Performance DNA','Actor Continuity Engine']),capabilities:Object.freeze(['emotion direction','voice direction','timing direction','blocking plans','gesture plans','performance continuity'])});
}
function actorContinuity(beats){
 const dimensions=['emotion','voice','blocking']; const drift=[];
 for(const d of dimensions){const values=[...new Set(beats.map(b=>clean(b[d])).filter(Boolean))];if(values.length>1)drift.push(Object.freeze({dimension:d,values:Object.freeze(values),code:'unapproved_performance_drift'}));}
 return Object.freeze({ok:drift.length===0,checkedDimensions:Object.freeze(dimensions),drift:Object.freeze(drift)});
}
export function buildPerformancePlan(input={}){
 const title=clean(input.title),character=clean(input.character); if(!title||!character)throw new Error('performance_lab_brief_incomplete');
 const beats=list(input.beats).map((b,i)=>Object.freeze({order:i+1,id:clean(b?.id)||'beat-'+String(i+1).padStart(2,'0'),emotion:clean(b?.emotion),voice:clean(b?.voice),blocking:clean(b?.blocking),status:'planned',mutationAllowed:false}));
 const blockers=[]; const consent=input.consentProof===true;
 if(input.usesRealPersonLikeness===true&&!consent)blockers.push(Object.freeze({code:'likeness_consent_required',gate:'likeness-consent',ownerAction:true}));
 if(input.usesSyntheticVoice===true&&!consent)blockers.push(Object.freeze({code:'voice_consent_required',gate:'voice-consent',ownerAction:true}));
 const continuity=actorContinuity(beats); if(!continuity.ok)blockers.push(Object.freeze({code:'actor_continuity_review_required',gate:'performance-continuity',ownerAction:false}));
 const dna=Object.freeze({character,lockedDimensions:Object.freeze(['approved voice','emotional range','mannerisms','timing','movement rules']),policy:'protected-performance-change-requires-review'});
 return Object.freeze({schema:'sauceapproved.studio.performance-lab.plan',version:1,title,character,performanceDna:dna,actorContinuity:continuity,beats:Object.freeze(beats),blockers:Object.freeze(blockers),planReady:blockers.length===0,executionReady:false,publishReady:false,mutationAttempted:false,nextGate:blockers.length?blockers[0].gate:'performance-proof-review'});
}
export function renderPerformanceLab(){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hercules Performance Lab</title><style>:root{font-family:Inter,system-ui,sans-serif;background:#070509;color:#fbf7ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#44243d,#110a12 38%,#070509 75%)}main{width:min(1160px,100%);margin:auto;padding:clamp(20px,5vw,58px)}a{color:#ffb8df;text-decoration:none}.hero{min-height:500px;display:grid;align-content:end;padding:clamp(28px,6vw,70px);border:1px solid #653752;border-radius:34px;background:linear-gradient(155deg,#34182b,#0a070b 72%)}.eyebrow{font-size:11px;letter-spacing:.23em;color:#f1a7cf}.hero h1{font-size:clamp(55px,10vw,110px);line-height:.82;letter-spacing:-.065em;margin:14px 0 22px}.hero p{max-width:820px;color:#d2bdc9;font-size:clamp(17px,2vw,22px);line-height:1.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px}.card{padding:28px;min-height:270px;border:1px solid #4c293e;border-radius:25px;background:#120b10}.card span{font-size:11px;letter-spacing:.17em;color:#d887b4}.card h2{font-size:30px;margin:50px 0 12px}.card p{color:#b49daa;line-height:1.6}.foot{margin-top:16px;padding:18px;border:1px solid #4c293e;border-radius:18px;color:#9d8794}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero{border-radius:24px;min-height:420px}}</style></head><body><main><a href="/">Back to SauceApproved Studio</a><section class="hero"><div class="eyebrow">SAUCEAPPROVED / DIRECTED DIGITAL PERFORMANCE</div><h1>Performance<br>Lab</h1><p>Direct emotion, voice, timing, gestures, and blocking as one protected performance system—without letting a character quietly become somebody else between shots.</p></section><section class="grid"><article class="card"><span>01 / CHARACTER</span><h2>Performance DNA</h2><p>Locks approved voice, emotional range, mannerisms, timing, and movement rules as the character travels through a production.</p></article><article class="card"><span>02 / CONTINUITY</span><h2>Actor Continuity Engine</h2><p>Flags unexplained changes in emotion, voice, and blocking before the performance moves toward execution.</p></article></section><div class="foot">Real-person likeness and synthetic voice remain consent-gated. Planning never equals permission to execute or publish.</div></main></body></html>`;}
