import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const css=`*{box-sizing:border-box}body{margin:0;font-family:ui-rounded,"Arial Rounded MT Bold",system-ui,sans-serif;background:linear-gradient(145deg,#07111f,#172554 55%,#312e81);color:#f8fafc;min-height:100vh}button{font:inherit}.shell{max-width:980px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}.brand{font-size:clamp(24px,5vw,42px);font-weight:900}.tag{color:#c7d2fe}.stats{display:flex;gap:8px;flex-wrap:wrap}.pill{background:#ffffff16;border:1px solid #ffffff26;border-radius:999px;padding:8px 12px}.hero{margin:20px 0;padding:24px;border-radius:28px;background:#ffffff18;border:1px solid #ffffff22}.hero h1{font-size:clamp(32px,8vw,64px);margin:0 0 8px}.worlds{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.world{min-height:170px;text-align:left;padding:20px;border:0;border-radius:24px;background:#fff;color:#111827;box-shadow:0 10px 30px #0004;cursor:pointer}.world strong{display:block;font-size:24px;margin:8px 0}.world .icon{font-size:30px;font-weight:1000}.progress{height:9px;background:#e5e7eb;border-radius:9px;overflow:hidden;margin-top:14px}.progress i{display:block;height:100%;background:#4f46e5}.game{max-width:720px;margin:25px auto;background:#fff;color:#111827;border-radius:28px;padding:24px}.game h2{font-size:clamp(26px,6vw,42px)}.choices{display:grid;gap:12px}.choice{padding:18px;border-radius:18px;border:2px solid #c7d2fe;background:#eef2ff;text-align:left;cursor:pointer}.feedback{font-weight:900;font-size:22px;margin:16px 0}.nav{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.nav button,.parent{border:0;border-radius:14px;padding:12px 16px;cursor:pointer}.parent{background:#111827;color:white}.report{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.card{padding:16px;background:#f1f5f9;border-radius:16px}@media(max-width:600px){.worlds{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.report{grid-template-columns:1fr}}`;

const js=`const W=[{id:"reading",name:"Word Woods",icon:"Aa",description:"Sound out words, spot rhymes, and build reading power."},{id:"math",name:"Number Nebula",icon:"123",description:"Count, add, subtract, and solve number missions."},{id:"science",name:"Discovery Bay",icon:"LAB",description:"Explore animals, weather, plants, Earth, and space."},{id:"logic",name:"Puzzle Peaks",icon:"?",description:"Find patterns, sequences, shapes, and clever solutions."}];
const B={reading:[["Which word starts with the /b/ sound?",["ball","cat","sun"],"ball","Say each word slowly."],["Which word rhymes with cat?",["hat","cup","dog"],"hat","Listen to the ending sound."],["Choose the word that completes: The dog can ___.",["run","blue","three"],"run","Which choice is something a dog can do?"]],math:[["What is 3 + 2?",["4","5","6"],"5","Start at 3 and count two more."],["Which number is bigger?",["7","4"],"7","Count up to each number."],["You have 8 stars and give away 3. How many remain?",["4","5","6"],"5","Count backward three times from 8."]],science:[["What do plants need to grow?",["water","toys","shoes"],"water","Think about what you give a houseplant."],["Which animal lives in water?",["fish","cat","chicken"],"fish","Which one swims all day?"],["What usually happens after water freezes?",["It becomes ice.","It becomes sand.","It disappears."],"It becomes ice.","Think about an ice tray."]],logic:[["What comes next? circle, square, circle, square, ...",["circle","triangle","star"],"circle","The two shapes repeat."],["Which one is different?",["apple","banana","chair"],"chair","Two choices are food."],["What comes next? 2, 4, 6, ...",["7","8","9"],"8","The numbers jump by two."]]};
const root=document.querySelector("#app");function fresh(){return{level:1,xp:0,streak:0,mastery:{reading:0,math:0,science:0,logic:0},completed:0}}let p;try{p=JSON.parse(localStorage.getItem("hercules-learning-player"))||fresh()}catch{p=fresh()}let a=null,n=0,f="";
function save(){localStorage.setItem("hercules-learning-player",JSON.stringify(p))}function q(){const l=B[a];return l[n%l.length]}function home(){a=null;f="";render()}function choose(x){a=x;n=0;f="";render()}function answer(c){const x=q(),ok=c===x[2];if(ok){p.xp+=10;p.streak+=1;p.completed+=1;p.mastery[a]=Math.min(10,p.mastery[a]+1);n+=1;f="Correct! +10 XP"}else{p.streak=0;p.mastery[a]=Math.max(0,p.mastery[a]-1);f="Good try. "+x[3]}p.level=1+Math.floor(p.xp/50);save();render()}
function report(){root.innerHTML='<div class="shell"><div class="game"><h2>Grown-up Progress</h2><p>Learning stays on this device. No child email, location, open chat, ads, or purchases are used.</p><div class="report">'+Object.entries(p.mastery).map(([k,v])=>'<div class="card"><strong>'+k.toUpperCase()+'</strong><p>Mastery '+v+' / 10</p></div>').join("")+'</div><p><strong>'+p.xp+' XP</strong> · Level '+p.level+' · '+p.completed+' challenges completed</p><div class="nav"><button id="back">Back to adventure</button></div></div></div>';document.querySelector("#back").onclick=home}
function render(){if(a){const w=W.find(x=>x.id===a),x=q();root.innerHTML='<div class="shell"><div class="game"><span>'+w.name+'</span><h2>'+x[0]+'</h2><div class="choices">'+x[1].map(c=>'<button class="choice">'+c+'</button>').join("")+'</div>'+(f?'<div class="feedback">'+f+'</div>':'')+'<p>Difficulty grows as skills grow.</p><div class="nav"><button id="home">Adventure map</button><span class="pill">XP '+p.xp+'</span></div></div></div>';document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>answer(b.textContent));document.querySelector("#home").onclick=home;return}root.innerHTML='<div class="shell"><header class="top"><div><div class="brand">HERCULES <span class="tag">LEARNING</span></div><small>Adventure mode · Ages 5–7</small></div><div class="stats"><span class="pill">Level '+p.level+'</span><span class="pill">'+p.xp+' XP</span><span class="pill">Streak '+p.streak+'</span></div></header><section class="hero"><h1>Pick your mission.</h1><p>Explore four worlds, earn XP, and build real skills.</p></section><section class="worlds">'+W.map(w=>'<button class="world" data-world="'+w.id+'"><span class="icon">'+w.icon+'</span><strong>'+w.name+'</strong><span>'+w.description+'</span><div class="progress"><i style="width:'+p.mastery[w.id]*10+'%"></i></div></button>').join("")+'</section><div class="nav"><span></span><button class="parent" id="parent">Grown-up Progress</button></div></div>';document.querySelectorAll("[data-world]").forEach(b=>b.onclick=()=>choose(b.dataset.world));document.querySelector("#parent").onclick=report}render();`;

Deno.serve((req:Request)=>{
 if(req.method!=="GET")return Response.json({error:"method_not_allowed"},{status:405,headers:{allow:"GET"}});
 const nonce=crypto.randomUUID().replaceAll("-","");
 const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#111827"><title>Hercules Learning Adventure</title><style nonce="'+nonce+'">'+css+'</style></head><body><main id="app"></main><script nonce="'+nonce+'">'+js+'</script></body></html>';
 return new Response(html,{headers:{
  "content-type":"text/html; charset=utf-8",
  "cache-control":"no-store",
  "content-security-policy":"default-src 'self'; connect-src 'none'; img-src 'self' data:; style-src 'nonce-"+nonce+"'; script-src 'nonce-"+nonce+"'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",
  "x-content-type-options":"nosniff",
  "referrer-policy":"no-referrer",
  "permissions-policy":"camera=(), microphone=(), geolocation=(), payment=()"
 }});
});
