export const HERCULES_BOOTSTRAP_CANDIDATES = Object.freeze([
  {
    version: "0.1",
    id: "hercules-core-bootstrap",
    family: "hercules-core",
    description: "Native bootstrap classifier for general-response mode selection; not the flagship general-reasoning model.",
    tasks: ["general"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:37538135e172d5893a0f3b9feef17d3c57c407d0e6aab56d8e2634b5b66621ed",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-coder-bootstrap",
    family: "hercules-coder",
    description: "Native bootstrap classifier for software-work intent; not the flagship code-generation model.",
    tasks: ["code"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:9f0fbb75e4b1db7391bbb2c4206a61310165758a700a497ee825f85fccb4c39e",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-vision-bootstrap",
    family: "hercules-vision",
    description: "Native bootstrap classifier for visual-request intent; it does not inspect pixels.",
    tasks: ["vision"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:288d955b8b5fce2e52b198e6275269aa2e7c606e27dcc365f8c86fd57aa53fd7",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-voice-bootstrap",
    family: "hercules-voice",
    description: "Native bootstrap classifier for voice-request intent; it does not decode or synthesize audio.",
    tasks: ["speech-to-text"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:d0d5aff155bd65317bbe7dccdb9d046582e21f7777c75bfdd6ba2e253574d13a",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-research-bootstrap",
    family: "hercules-research",
    description: "Native bootstrap classifier for research-strategy selection; not the flagship evidence-synthesis model.",
    tasks: ["research"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:89f8b5f8dbc9a39423b2a3c75be7a0419cdc2664bf0fc5dff622cb34e327c936",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-retrieval-bootstrap",
    family: "hercules-retrieval",
    description: "Native TF-IDF lexical retriever for Hercules-owned documentation; not the future neural embedding model.",
    tasks: ["rerank"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:83f2010b8c039470cca6414e63adfe6eb3d14b7665c7cadcb7317ddf9ebed2ce",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-guard-bootstrap",
    family: "hercules-guard",
    description: "Native bootstrap classifier for action-risk routing; deterministic authorization remains authoritative.",
    tasks: ["safety"],
    state: "candidate",
    origin: "hercules-native",
    priority: 100,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:98b3f0b10a0ac79b813aed3f44b74f5353edf49bcb9d6356a37787260c2bc77e",
    provenance: "Attested in hercules-models/attestations/hercules-family-bootstrap-v0.1.json.",
  },
]);
