export const HERCULES_MODEL_SLOTS = Object.freeze([
  {
    version: "0.1",
    id: "hercules-core",
    family: "hercules-core",
    description: "Native v0.1 general-response mode classification for Hercules control.",
    tasks: ["general"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:095cfc427f2e0de60df0ffc6d7865d3b861ceff65fb68dc4ba39f243d857c83b",
    provenance: "Attested in hercules-models/attestations/hercules-core-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-coder",
    family: "hercules-coder",
    description: "Native v0.1 software-work classification for build, debug, test, and review control.",
    tasks: ["code"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:59fdb5feb39bdcaecd876fa078d6a06f3fa086e70ca19bef11522f12a784f053",
    provenance: "Attested in hercules-models/attestations/hercules-coder-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-vision",
    family: "hercules-vision",
    description: "Native v0.1 visual-request routing for inspect, OCR, compare, and UI-analysis control; pixel understanding remains a later capability.",
    tasks: ["vision"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:fb9d35b882329104ff142ee2dbd3131a74891db9deae2269183d4973ff9ecd6c",
    provenance: "Attested in hercules-models/attestations/hercules-vision-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-voice",
    family: "hercules-voice",
    description: "Native v0.1 voice-request routing for transcribe, synthesize, translate, and summarize control; audio decoding and synthesis remain later capabilities.",
    tasks: ["speech-to-text", "text-to-speech"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:46f91666a83ed86981b3605e2e1e53ccf2ea70ad2d20abf465684d34115a7004",
    provenance: "Attested in hercules-models/attestations/hercules-voice-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-research",
    family: "hercules-research",
    description: "Native v0.1 research-strategy classification for current, primary-source, comparison, and verification control.",
    tasks: ["research"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:7bfc399aa0118873b5cba1923a1c0f36f79ecb06534cd2df683e84808fe953d9",
    provenance: "Attested in hercules-models/attestations/hercules-research-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-agent",
    family: "hercules-agent",
    description: "Native intent routing for Hercules agent orchestration.",
    tasks: ["agent"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:ae3475d53cc75959bc52ca7e6bd39b6c84b693c71a2dbcac28977a65a220f618",
    provenance: "Attested in hercules-models/attestations/hercules-agent-router-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-retrieval",
    family: "hercules-retrieval",
    description: "Native sparse embeddings and reranking for Hercules memory and search.",
    tasks: ["embedding", "rerank"],
    state: "active",
    origin: "hercules-native",
    priority: 900,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:6904b2617443a36377cfe20eb1010579d50df479041bece6bc7d8ce032543fa4",
    provenance: "Attested in hercules-models/attestations/hercules-retrieval-v0.1.json.",
  },
  {
    version: "0.1",
    id: "hercules-guard",
    family: "hercules-guard",
    description: "Native action-policy classification for Hercules control decisions.",
    tasks: ["safety"],
    state: "active",
    origin: "hercules-native",
    priority: 1000,
    runtime: {kind: "embedded", endpoint: null},
    checkpoint: "sha256:f6e6a598aa1183234ab7e9d06ace6e79bf25f87d3f53746767f162d9115425d4",
    provenance: "Attested in hercules-models/attestations/hercules-guard-v0.1.json.",
  },
]);
