export const HERCULES_MODEL_SLOTS = Object.freeze([
  {
    version: "0.1",
    id: "hercules-core",
    family: "hercules-core",
    description: "General Hercules reasoning and instruction model.",
    tasks: ["general"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoint to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-coder",
    family: "hercules-coder",
    description: "Software engineering, debugging, repository, and code-generation model.",
    tasks: ["code"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoint to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-vision",
    family: "hercules-vision",
    description: "Image, screenshot, document, and interface understanding model.",
    tasks: ["vision"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoint to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-voice",
    family: "hercules-voice",
    description: "Speech recognition and speech synthesis model family.",
    tasks: ["speech-to-text", "text-to-speech"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoints to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-research",
    family: "hercules-research",
    description: "Retrieval-aware research and evidence synthesis model.",
    tasks: ["research"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoint to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-agent",
    family: "hercules-agent",
    description: "Tool selection, workflow planning, and agent-control model.",
    tasks: ["agent"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoint to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-retrieval",
    family: "hercules-retrieval",
    description: "Embedding and reranking model family for Hercules memory and search.",
    tasks: ["embedding", "rerank"],
    state: "planned",
    origin: "hercules-native",
    priority: 900,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoints to be trained under Hercules provenance controls.",
  },
  {
    version: "0.1",
    id: "hercules-guard",
    family: "hercules-guard",
    description: "Policy, permission, secret-handling, and action-validation model.",
    tasks: ["safety"],
    state: "planned",
    origin: "hercules-native",
    priority: 1000,
    runtime: null,
    checkpoint: null,
    provenance: "Native checkpoint to be trained under Hercules provenance controls.",
  },
]);
