import {WORLDS,createPlayer,gradeAnswer,nextChallenge,summarizeProgress} from "./engine.mjs";
const root=document.querySelector("#app");let player=load();let active=null;let question=0;let feedback="";
function load(){try{return JSON.parse(localStorage.getItem("hercules-learning-player"))||createPlayer()}catch{return createPlayer()}}
function save(){localStorage.setItem("hercules-learning-player",JSON.stringify(player))}
function home(){active=null;feedback="";render()}
function choose(subject){active=subject;question=0;feedback="";render()}
function answer(choice){const q=nextChallenge(player,active,question);const correct=choice===q.answer;player=gradeAnswer(player,{subject:active,correct});save();feedback=correct?"Correct! +10 XP":"Good try. "+q.hint;if(correct)question+=1;render()}
function report(){const s=summarizeProgress(player);root.innerHTML='<div class="shell"><div class="game"><h2>Grown-up Progress</h2><p>Learning stays on this device. No child email, location, open chat, ads, or purchases are used.</p><div class="report">'+Object.entries(s.mastery).map(([k,v])=>'<div class="card"><strong>'+k.toUpperCase()+'</strong><p>Mastery '+v+' / 10</p></div>').join("")+'</div><p><strong>'+s.totalXp+' XP</strong> · Level '+s.level+' · '+s.completed+' challenges completed</p><div class="nav"><button id="back">Back to adventure</button></div></div></div>';document.querySelector("#back").onclick=home}
function render(){if(active){const w=WORLDS.find(x=>x.id===active),q=nextChallenge(player,active,question);root.innerHTML='<div class="shell"><div class="game"><span>'+w.name+'</span><h2>'+q.prompt+'</h2><div class="choices">'+q.choices.map(c=>'<button class="choice">'+c+'</button>').join("")+'</div>'+(feedback?'<div class="feedback">'+feedback+'</div>':'')+'<div class="hint">Hint available after a try. Difficulty adjusts as skills grow.</div><div class="nav"><button id="home">Adventure map</button><span class="pill">XP '+player.xp+'</span></div></div></div>';document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>answer(b.textContent));document.querySelector("#home").onclick=home;return}
root.innerHTML='<div class="shell"><header class="top"><div><div class="brand">HERCULES <span class="tag">LEARNING</span></div><small>Adventure mode · Ages 5–7</small></div><div class="stats"><span class="pill">Level '+player.level+'</span><span class="pill">'+player.xp+' XP</span><span class="pill">Streak '+player.streak+'</span></div></header><section class="hero"><h1>Pick your mission.</h1><p>Every challenge gets smarter as you learn. Explore four worlds, earn XP, and build real skills.</p></section><section class="worlds">'+WORLDS.map(w=>'<button class="world" data-world="'+w.id+'"><span class="icon">'+w.icon+'</span><strong>'+w.name+'</strong><span>'+w.description+'</span><div class="progress"><i style="width:'+player.mastery[w.id]*10+'%"></i></div></button>').join("")+'</section><div class="nav"><span></span><button class="parent" id="parent">Grown-up Progress</button></div></div>';document.querySelectorAll("[data-world]").forEach(b=>b.onclick=()=>choose(b.dataset.world));document.querySelector("#parent").onclick=report}
render();