const KITS=Object.freeze([
  Object.freeze({id:"hero",name:"Neighborhood Hero",genre:"Adventure",accent:"#e9a662",summary:"Make a three-shot story about helping someone in your world.",differentiators:["Choice Compass — try two decisions and see how the story changes","Courage Replay — build an alternate ending that celebrates a different kind of bravery"]}),
  Object.freeze({id:"director",name:"Dream Director",genre:"Creative spotlight",accent:"#d6a9ec",summary:"Direct a short performance, story, or style film on your terms.",differentiators:["Beat Board — arrange shots on a silent rhythm grid","Role Swap — plan both the director and performer view of the same scene"]}),
  Object.freeze({id:"capsule",name:"Time Capsule",genre:"Family keepsake",accent:"#9bd9c7",summary:"Capture a moment today and make a note for the future.",differentiators:["Then / Now — pair a present-day shot with a future reflection","Privacy Check — catch obvious personal details in the script before export"]})
]);

export function createKidsStudioManifest(){
  return Object.freeze({schema:"sauceapproved.studio.kids",version:1,product:"SauceApproved Kids Studio",audience:"parent-operated family creation",storage:"device-only",serverUpload:false,childAccounts:false,publishing:false,executionPolicy:"parent-review-required",kits:KITS});
}

export function renderKidsStudio(){
  const cards=KITS.map((kit,index)=>`<button class="kit" type="button" data-kit="${kit.id}" style="--accent:${kit.accent}" aria-pressed="${index===0}">
    <span class="number">0${index+1} / ${kit.genre}</span><strong>${kit.name}</strong><span>${kit.summary}</span>
    <small>${kit.differentiators.map(value=>`<span>✦ ${value}</span>`).join("")}</small>
  </button>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Kids Studio — SauceApproved</title><meta name="description" content="Three parent-operated story kits in the Hercules vintage camera studio.">
<style>
:root{font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;color:#f6eee3;background:#090b0e;--gold:#e8bc78}*{box-sizing:border-box}
body{margin:0;background:radial-gradient(circle at 70% -20%,#3e302e 0,#11151b 40%,#090b0e 75%);min-height:100vh}
main{max-width:1260px;margin:auto;padding:clamp(18px,4vw,48px)}a{color:inherit}.back{font-size:13px;color:#c4b3a0;text-decoration:none;font-weight:800}
.mast{display:flex;justify-content:space-between;align-items:center;gap:20px;margin:36px 0 16px}.over{color:var(--gold);letter-spacing:.22em;text-transform:uppercase;font-size:11px;font-weight:900}
h1{font-size:clamp(48px,9vw,110px);line-height:.89;letter-spacing:-.075em;margin:12px 0 22px}h1 em{font-style:normal;color:var(--gold)}.intro{max-width:680px;color:#bdb3aa;font-size:18px}
.dial{width:130px;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;text-align:center;color:#f7e4c5;font-size:12px;letter-spacing:.14em;font-weight:900;border:12px ridge #7f6147;box-shadow:0 0 0 8px #1a1818,0 25px 40px #0009;background:radial-gradient(circle,#513829,#1e1714)}
.kits{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:42px 0 20px}.kit{appearance:none;text-align:left;padding:25px;min-height:315px;border:1px solid #3a3736;border-radius:23px;background:linear-gradient(145deg,#252428,#14171d);color:inherit;cursor:pointer;display:flex;flex-direction:column;gap:16px;transition:transform .2s,border-color .2s}.kit:hover,.kit:focus-visible{transform:translateY(-4px);border-color:var(--accent)}.kit[aria-pressed=true]{border-color:var(--accent);box-shadow:inset 0 3px var(--accent),0 15px 50px #0007}.kit .number{color:var(--accent);font-size:12px;letter-spacing:.15em;text-transform:uppercase;font-weight:900}.kit strong{font-size:clamp(26px,3vw,38px);line-height:1;letter-spacing:-.05em}.kit>span:not(.number){color:#d1c7bf}.kit small{display:grid;gap:8px;margin-top:auto;color:#d0c2b5;font-size:12px;line-height:1.45}
.console{border:1px solid #685540;background:linear-gradient(150deg,#332b25,#15191d 56%);border-radius:28px;padding:clamp(20px,4vw,42px);box-shadow:0 25px 80px #0008}.console-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.lamp{color:#efd2ae;font-size:11px;font-weight:900;letter-spacing:.15em}.lamp:before{content:"";display:inline-block;width:9px;height:9px;margin-right:8px;border-radius:50%;background:#f2775e;box-shadow:0 0 14px #ff745e}
h2{font-size:clamp(30px,5vw,52px);letter-spacing:-.05em;margin:20px 0 6px}.muted{color:#baa99a}.work{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-top:25px}label{display:block;margin:14px 0;font-size:13px;font-weight:800;color:#e4d8c9}input,select,textarea{display:block;width:100%;margin-top:7px;background:#111419;border:1px solid #6a5749;border-radius:11px;padding:12px;color:#fff;font:inherit}textarea{resize:vertical;min-height:90px}
.feature{border:1px solid #665344;border-radius:18px;padding:20px;background:#18191bd9}.feature h3{margin:0;font-size:20px}.feature p{margin:7px 0;color:#bbaea0;font-size:13px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:25px}button.action,a.action{border:1px solid #82634b;border-radius:12px;padding:13px 18px;background:#e8bc78;color:#1b1510;font-weight:900;text-decoration:none;cursor:pointer}.action.secondary{background:#25282c;color:#e8d7c4}button:disabled{opacity:.42;cursor:not-allowed}
.review{border:1px solid #88704f;border-radius:16px;padding:17px;margin-top:22px;background:#241f1b}.review label{font-weight:500}.review input{display:inline;width:auto;margin:0 8px 0 0}.note{font-size:12px;color:#bbaea0;margin-top:18px}.output{white-space:pre-wrap;background:#0b0d10;border:1px solid #635140;padding:20px;border-radius:16px;margin-top:18px;color:#e9dfd1;min-height:90px}.output:empty{display:none}
@media(max-width:800px){.kits{grid-template-columns:1fr}.kit{min-height:0}.work{grid-template-columns:1fr}.dial{width:85px;border-width:8px;font-size:9px}.mast{align-items:flex-start}}
</style></head><body><main><a class="back" href="/">← SAUCEAPPROVED STUDIO</a><div class="mast"><div><div class="over">HERCULES / FAMILY FILM DIVISION</div><h1>Little stories.<br><em>Big screen.</em></h1><p class="intro">Three original story kits, one vintage camera spirit. A parent or guardian operates this workspace and reviews the plan before saving it.</p></div><div class="dial" aria-hidden="true">STORY<br>MODE<br>●</div></div>
<section class="kits" aria-label="Choose a story kit">${cards}</section>
<section class="console" aria-labelledby="workspace-title"><div class="console-head"><span class="lamp">HERCULES / VIEWFINDER</span><span class="over">PRIVATE DRAFT / DEVICE ONLY</span></div><h2 id="workspace-title">Neighborhood Hero</h2><p id="description" class="muted">Choose a decision, then see another way the hero could help.</p>
<div class="work"><div><label>Story title <input id="title" maxlength="80" placeholder="A small act of courage" autocomplete="off"></label><label>Scene idea (keep names and locations private)<textarea id="idea" maxlength="400" placeholder="A friend needs help carrying something..."></textarea></label><div id="kit-controls"></div></div><div><div class="feature"><h3 id="feature-title">Choice Compass</h3><p id="feature-description"></p><div id="feature-controls"></div></div><div class="feature" style="margin-top:14px"><h3 id="feature-two-title">Courage Replay</h3><p id="feature-two-description"></p><div id="feature-two-controls"></div></div></div></div>
<div class="review"><strong>Parent review required</strong><label><input id="parent" type="checkbox"> I am a parent or guardian operating this tool, and I reviewed this draft for personal details and permission to film anyone shown.</label></div>
<div class="actions"><button class="action" id="preview" type="button">Preview shot plan</button><button class="action secondary" id="save" type="button" disabled>Save reviewed plan</button><a class="action secondary" href="/vintage-camera">Open vintage camera ↗</a></div><div id="message" class="note" role="status" aria-live="polite">No account, upload, cloud generation, or public posting is available here.</div><div id="output" class="output" aria-live="polite"></div></section>
<p class="note">This planner stores no draft on the server. Saving downloads a text plan to your device. The camera is a separate local-first tool; it does not automatically receive this draft. Keep a parent present when recording or sharing children’s media.</p></main><script src="/assets/kids-studio.js" defer></script></body></html>`;
}
