import {createCreationFloorManifest} from "./core.mjs";
export function renderCreationFloor(){
 const m=createCreationFloorManifest();
 const cards=m.systems.map((s,i)=>`<article class="card"><span>${String(i+1).padStart(2,"0")}</span><h2>${s.label}</h2><p>${s.purpose}</p><b>${s.status}</b></article>`).join("");
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Hercules Creation Floor</title><style>
 :root{font-family:Inter,ui-sans-serif,system-ui;background:#050505;color:#f7f7f7}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#29190f 0,#0b0908 36%,#030303 75%)}main{width:min(1180px,100%);margin:auto;padding:clamp(16px,4vw,42px)}a{color:#aaa;text-decoration:none;font-weight:800}.hero,.workspace{border:1px solid #3a2a20;background:linear-gradient(145deg,#1a120d,#090909);box-shadow:0 28px 100px #0009}.hero{margin-top:20px;padding:clamp(24px,5vw,54px);border-radius:30px}.eyebrow{font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:#d49a73}h1{font-size:clamp(46px,9vw,90px);line-height:.9;letter-spacing:-.06em;margin:12px 0 18px}h1 em{font-style:normal;color:#efb181}.lead{max-width:820px;color:#b9b9b9;font-size:clamp(16px,2vw,20px);line-height:1.6}.locks,.tools{display:flex;gap:8px;flex-wrap:wrap;margin-top:20px}.pill,.tool{font:800 11px/1 system-ui;letter-spacing:.05em;border:1px solid #5b3926;border-radius:999px;padding:10px 12px;color:#e6b28e;background:#160e09}.workspace{margin-top:18px;border-radius:26px;padding:18px}.bar{display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.bar h2{margin:4px 0;font-size:24px}.status{color:#efb181;font-size:12px;font-weight:900}.editor{display:grid;grid-template-columns:230px 1fr;gap:12px;margin-top:16px}.panel,.timeline{border:1px solid #29231f;border-radius:18px;background:#080808;padding:14px}.panel h3,.timeline h3{margin:0 0 12px}.asset{border:1px solid #28231f;border-radius:13px;padding:11px;margin:8px 0;color:#bbb}.asset b{display:block;color:#eee;margin-bottom:3px}.track{display:grid;grid-template-columns:72px 1fr;gap:8px;align-items:center;margin:10px 0}.track>span{font-size:11px;color:#999}.rail{min-height:58px;border:1px solid #24201d;border-radius:12px;padding:7px;background:#040404;display:flex;gap:6px;overflow:hidden}.clip{min-width:120px;border:1px solid #6a422c;border-radius:9px;background:#1c110b;padding:9px;color:#efc3a5;font-size:11px}.clip small{display:block;color:#9e816e;margin-top:5px}.hint{color:#777;font-size:12px;line-height:1.5}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:18px}.card{padding:22px;min-height:190px;border:1px solid #29231f;border-radius:22px;background:#0c0b0aee}.card span{font-size:11px;letter-spacing:.18em;color:#a77a5c}.card h2{margin:28px 0 8px;font-size:23px}.card p{color:#999;line-height:1.5}.card b{font-size:11px;text-transform:uppercase;color:#d49a73}@media(max-width:720px){.grid,.editor{grid-template-columns:1fr}.hero,.workspace{border-radius:22px}.track{grid-template-columns:58px 1fr}.rail{overflow-x:auto}.clip{min-width:108px}}
 </style></head><body><main><a href="/">← SauceApproved Studio</a><section class="hero"><div class="eyebrow">SauceApproved Studio / Hercules production layer</div><h1>Creation <em>Floor</em></h1><p class="lead">One production path from project and owned media through edit, captions, audio, recovery, review, controlled publishing and verified performance evidence.</p><div class="locks"><b class="pill">Proof Spine</b><b class="pill">Creative DNA Guard</b><b class="pill">Publishing fail-closed</b></div></section>
 <section class="workspace" aria-label="Timeline Editor workspace"><div class="bar"><div><div class="eyebrow">Working surface</div><h2>Timeline Editor</h2></div><div class="status">Export locked · renderer verification required</div></div><div class="tools"><button class="tool" type="button">Add media</button><button class="tool" type="button">Split</button><button class="tool" type="button">Trim</button><button class="tool" type="button">Move</button><button class="tool" type="button" disabled>Export locked</button></div>
 <div class="editor"><aside class="panel"><h3>Project Hub</h3><div class="asset"><b>Current project</b>Untitled Hercules project</div><h3>Media Vault</h3><div class="asset"><b>Video</b>Owner media · rights checked</div><div class="asset"><b>Audio</b>Proof Spine attached</div><p class="hint">Media remains source-preserving. Unknown rights never become export-ready automatically.</p></aside>
 <section class="timeline"><h3>Multitrack timeline</h3><div class="track" data-timeline-track="video-1"><span>VIDEO 1</span><div class="rail"><div class="clip" data-clip="clip-1">Primary clip<small>00:00 → 00:05</small></div><div class="clip" data-clip="clip-2">B-roll<small>00:05 → 00:08</small></div></div></div><div class="track" data-timeline-track="overlay-1"><span>OVERLAY</span><div class="rail"><div class="clip" data-clip="overlay-1">SauceApproved title<small>non-destructive</small></div></div></div><div class="track" data-timeline-track="audio-1"><span>AUDIO</span><div class="rail"><div class="clip" data-clip="audio-1">Voice / music<small>rights-aware</small></div></div></div><p class="hint">Move, trim, split and remove operations preserve original source ranges. Rendering stays closed until a verified renderer and project approval are present.</p></section></div></section>
 <section class="grid">${cards}</section></main></body></html>`;
}
